[colors]
ansi = [
    "#fbf7f0",
    "#a60000",
    "#006800",
    "#6f5500",
    "#0031a9",
    "#721045",
    "#005e8b",
    "#000000",
]
background = "#fbf7f0"
brights = [
    "#efe9dd",
    "#d00000",
    "#008900",
    "#808000",
    "#0000ff",
    "#dd22dd",
    "#008899",
    "#595959",
]
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#fbf7f0"
foreground = "#000000"

[colors.indexed]

[metadata]
aliases = []
name = "Modus Operandi Tinted (Gogh)"
origin_url = "https://github.com/Gogh-Co/Gogh"
wezterm_version = "nightly builds only"
